import { NextResponse } from 'next/server'

// Mock data for student marks
// In production, this would fetch from database
export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100))

  const marksData = {
    currentCGPA: 8.5,
    recentMarks: [
      {
        id: '1',
        subject: 'Data Structures & Algorithms',
        subjectCode: 'CS301',
        examType: 'Mid Semester',
        maxMarks: 50,
        obtainedMarks: 45,
        percentage: 90,
        grade: 'O',
        date: '2024-03-15',
      },
      {
        id: '2',
        subject: 'Database Management Systems',
        subjectCode: 'CS302',
        examType: 'Mid Semester',
        maxMarks: 50,
        obtainedMarks: 42,
        percentage: 84,
        grade: 'A',
        date: '2024-03-14',
      },
      {
        id: '3',
        subject: 'Operating Systems',
        subjectCode: 'CS303',
        examType: 'Mid Semester',
        maxMarks: 50,
        obtainedMarks: 38,
        percentage: 76,
        grade: 'B+',
        date: '2024-03-13',
      },
      {
        id: '4',
        subject: 'Computer Networks',
        subjectCode: 'CS304',
        examType: 'Mid Semester',
        maxMarks: 50,
        obtainedMarks: 35,
        percentage: 70,
        grade: 'B',
        date: '2024-03-12',
      },
      {
        id: '5',
        subject: 'Software Engineering',
        subjectCode: 'CS305',
        examType: 'Assignment',
        maxMarks: 30,
        obtainedMarks: 28,
        percentage: 93,
        grade: 'O',
        date: '2024-03-10',
      },
      {
        id: '6',
        subject: 'Machine Learning',
        subjectCode: 'CS306',
        examType: 'Quiz',
        maxMarks: 20,
        obtainedMarks: 16,
        percentage: 80,
        grade: 'A',
        date: '2024-03-08',
      },
    ],
    semesterPerformance: [
      { semester: 'Sem 1', gpa: 7.8, credits: 22, status: 'Completed' },
      { semester: 'Sem 2', gpa: 8.0, credits: 24, status: 'Completed' },
      { semester: 'Sem 3', gpa: 8.2, credits: 24, status: 'Completed' },
      { semester: 'Sem 4', gpa: 8.4, credits: 26, status: 'Completed' },
      { semester: 'Sem 5', gpa: 8.5, credits: 24, status: 'Completed' },
      { semester: 'Sem 6', gpa: 8.5, credits: 22, status: 'Ongoing' },
    ],
    gpaTrend: [
      { semester: 'S1', gpa: 7.8, credits: 22 },
      { semester: 'S2', gpa: 8.0, credits: 24 },
      { semester: 'S3', gpa: 8.2, credits: 24 },
      { semester: 'S4', gpa: 8.4, credits: 26 },
      { semester: 'S5', gpa: 8.5, credits: 24 },
      { semester: 'S6', gpa: 8.5, credits: 22 },
    ],
    subjectWisePerformance: [
      {
        subject: 'Data Structures & Algorithms',
        code: 'CS301',
        internal: 28,
        midSem: 45,
        assignment: 28,
        total: 101,
        maxTotal: 120,
        grade: 'O',
      },
      {
        subject: 'Database Management Systems',
        code: 'CS302',
        internal: 26,
        midSem: 42,
        assignment: 25,
        total: 93,
        maxTotal: 120,
        grade: 'A',
      },
      {
        subject: 'Operating Systems',
        code: 'CS303',
        internal: 24,
        midSem: 38,
        assignment: 22,
        total: 84,
        maxTotal: 120,
        grade: 'B+',
      },
      {
        subject: 'Computer Networks',
        code: 'CS304',
        internal: 22,
        midSem: 35,
        assignment: 20,
        total: 77,
        maxTotal: 120,
        grade: 'B',
      },
      {
        subject: 'Software Engineering',
        code: 'CS305',
        internal: 25,
        midSem: 32,
        assignment: 28,
        total: 85,
        maxTotal: 120,
        grade: 'B+',
      },
      {
        subject: 'Machine Learning',
        code: 'CS306',
        internal: 24,
        midSem: 30,
        assignment: 18,
        total: 72,
        maxTotal: 120,
        grade: 'B',
      },
    ],
    summary: {
      totalCreditsEarned: 142,
      totalCreditsRequired: 160,
      standing: 'First Class with Distinction',
      rank: 12,
      totalStudents: 120,
    },
  }

  return NextResponse.json(marksData)
}
